{% set name = "eli5" %}
{% set version = "0.14.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d5d110533c203026aaeb5c673c6e77ac67dd5daf18394e2c27ebd0cb4c2e2d45

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ pytjon_min }}
    - attrs >17.1.0
    - jinja2 >=3.0.0
    - numpy >=1.9.0
    - scipy
    - singledispatch >=3.4.0.3
    - six
    - scikit-learn >=1.6.0
    - python-graphviz
    - tabulate >=0.7.7

test:
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check
  imports:
    - eli5

about:
  home: https://eli5.readthedocs.io/
  license: MIT
  license_file: LICENSE.txt
  summary: Debug machine learning classifiers and explain their predictions
  description: |
    ELI5 is a Python package which helps to debug machine learning classifiers
    and explain their predictions.
  doc_url: https://eli5.readthedocs.io/en/latest/
  dev_url: https://github.com/TeamHG-Memex/eli5/

extra:
  recipe-maintainers:
    - rmax
    - xhochy
